### ISSUE TITLE
Nested Form Issue #GSSoC2024exd

### ISSUE THREAD

**Issue by Prerrna** [Ramsey99/Admin_Dashboard#10]

**Comment by Prerrna** [comment]
assign me i will fix

**Comment by simmi-verma** [comment]
I would like to contribute in it .Please add label of gssoc-ext 24 and assign to me.

**Comment by VaishnaviLakade** [comment]
I would like to contribute please assign it to me

**Comment by Prerrna** [comment]
can you please add the lables GSSoC and GSSoC2024Extd
