### ISSUE TITLE
Layout and Spacing Issues on Admin Dashboard

### ISSUE THREAD

**Issue by Sunilkumarchavhan9** [Ramsey99/Admin_Dashboard#12]
The current admin dashboard has layout, spacing, and structural problems, impacting the user interface and user experience. The specific issues are as follows:

1. Excessive White Space: There is a large amount of unnecessary space between the "Sign In" and "Sign Up" sections, as well as between the welcome message and other page elements.

2. Redundant Content: The "Welcome to Bus Tracking System" message is duplicated unnecessarily, confusing users.

3. Alignment Problems: Input fields, labels, and buttons are misaligned, creating a disorganized look.

4.Inconsistent Styling: Buttons and form fields lack proper styling, making them look plain and disconnected from the overall theme of the project.

Expected Behavior:

Reduce the white space between sections for better flow.

Remove redundant "Welcome to Bus Tracking System" messages.

Align buttons, fields, and labels consistently.

Apply proper CSS styling to buttons and input fields for a cohesive look and feel.

![Screenshot 2024-10-02 234842](https://github.com/user-attachments/assets/14cbfc36-7f91-485b-af94-ec5db329d0a3)

 can u assign this issue to me I from am gssoc24 extend could u assign me

**Comment by SahilCharan** [comment]
i want to work on same, please assign me

**Comment by Vipulsnips** [comment]
Hi @Ramsey99 I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

Thanks so much!
