### ISSUE TITLE
Incorporate contact info and other imp link in footer.

### ISSUE THREAD

**Issue by Aditi-008** [Ramsey99/Admin_Dashboard#15]
In footer contact info for any issue and other stuffs like link to different pages, schedule etc would be added. Email section also provided for complain etc.

**Comment by Riya7045** [comment]
please assign this issue to me and also add labels.

**Comment by komalnalage** [comment]
Hi @Ramsey99  I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

Thanks so much!
