### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [Ramsey99/Admin_Dashboard#16]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by Shariq2003** [comment]
@Ramsey99 please add label for level of Gssoc Ext for this isse.

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?

**Comment by SuyashSingh01** [comment]
Hi @Ramsey99 , the issue is still open if  want to assign me I would like to contribute  to this issue.

**Comment by Shariq2003** [comment]
@Ramsey99 My PR have merged but you have not added label of level to that, please do.
