### ISSUE TITLE
Update Twitter Icon to Reflect Rebranding as X

### ISSUE THREAD

**Issue by Vishwajeet594** [Ramsey99/Admin_Dashboard#45]
### Issue: Update the social media icon for Twitter to reflect its rebranding as "X." The icon should be replaced on all pages where the Twitter link appears to maintain consistency across the website. Ensure the new icon aligns with the overall design aesthetic of the site.
![Screenshot 2024-10-09 183941](https://github.com/user-attachments/assets/75546d81-2ee0-4cb0-b4c4-c40e61c70555)

**Comment by gurramkarthiknetha** [comment]
i wanted to fix Update Twitter Icon to Reflect Rebranding as X #45

**Comment by Vishwajeet594** [comment]
sir why u assign this issue to another i was raise this issue
