### ISSUE TITLE
Contact Link Not Working 

### ISSUE THREAD

**Issue by Vishwajeet594** [Ramsey99/Admin_Dashboard#55]
### Description: 
**The contact link on the [specific page or section] is currently not functioning as expected. When clicked, it either leads to a 404 error page or doesn't redirect to the intended contact form/email.**
![Screenshot 2024-10-11 095032](https://github.com/user-attachments/assets/5020d589-3a9e-4958-89ce-c0920f130e2e)

**Comment by SaanyaGarg5** [comment]
you can assign me this task... under gsso-ext and hacktoberfest and level 3 label..

**Comment by Vishwajeet594** [comment]
Bro find ur own issue
