### ISSUE TITLE
Add contact section 

### ISSUE THREAD

**Issue by shraddhabaghel** [Ramsey99/Admin_Dashboard#8]
i will add contact section to make it easier for user to get details if he she wants any additional info

**Comment by shraddhabaghel** [comment]
Please assign me this issue

**Comment by simmi-verma** [comment]
I would like to contribute in it .Please add label of gssoc-ext 24 and assign to me.

**Comment by prachithakor08** [comment]
I would like to contribute in this project .I will make a attractive contact page .Please assign this issue to me

**Comment by Riya7045** [comment]
I'd love to contribute to this project by working on the Contact Page. I plan to redesign it to be visually appealing, user-friendly, and aligned with modern UI/UX trends. With a focus on accessibility and responsiveness, I aim to make it not just functional but captivating for users. Please assign this issue to me, and I'll ensure the page stands out!

**Comment by komalnalage** [comment]
Hi @shraddhabaghel I would like to work on this issue .Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

Thanks so much!

**Comment by Kedarnath-Rothe** [comment]
Please assign this is to me under hactoberfest
